version: '3.9'

services: 
  db:
    image: postgres:16 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mqpz7Mqpz7
      POSTGRES_DB: Company 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "1735:5432"
    networks:
      - app-network
  web:
    build: .
    environment:
      DB_URL: postgresql://postgres:Mqpz7Mqpz7@db:5432/Company
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: