FROM python:3.9-slim

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . /Project
WORKDIR /Project
CMD ["uvicorn","Project.main:app","--host","0.0.0.0","--port","8000"]